name: Build Android APK & Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: |
          cd android-app
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --stacktrace

      - name: Find APK
        id: apkfile
        run: |
          APK=$(find $GITHUB_WORKSPACE -name "*debug.apk" | head -n 1)
          echo "apk=$APK" >> $GITHUB_OUTPUT
          echo "Found APK: $APK"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Google API SDK
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Upload to Google Drive
        id: upload
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          APK_FILE: ${{ steps.apkfile.outputs.apk }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > service.json
          python3 <<EOF
import datetime
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

creds = service_account.Credentials.from_service_account_file(
    "service.json",
    scopes=["https://www.googleapis.com/auth/drive"]
)

drive = build("drive", "v3", credentials=creds)

date = datetime.datetime.now().strftime("%Y-%m-%d")
query = f"name='{date}' and mimeType='application/vnd.google-apps.folder'"
res = drive.files().list(q=query, spaces='drive').execute().get('files', [])

if res:
    folder_id = res[0]['id']
else:
    folder = drive.files().create(
        body={"name": date, "mimeType": "application/vnd.google-apps.folder"},
        fields="id"
    ).execute()
    folder_id = folder['id']

media = MediaFileUpload(
    "${APK_FILE}",
    mimetype="application/vnd.android.package-archive",
    resumable=True
)

file_metadata = {"name": "app-debug.apk", "parents": [folder_id]}

file = drive.files().create(
    body=file_metadata,
    media_body=media,
    fields="id"
).execute()

file_id = file.get("id")
print("DOWNLOAD_URL=https://drive.google.com/uc?id=" + file_id)
EOF

      - name: Show Download Link
        run: echo "Google Drive Download URL: ${{ steps.upload.outputs.DOWNLOAD_URL }}"

